### ISSUE TITLE
Help-Page no está 100% oculta en Desktop

### ISSUE THREAD

**Issue by mp19uy** [HiroAgustin/DondeReciclo#12]
Cuando se entra a la página desde una pc desktop, la página de ayuda que se visualiza al tocar el boton de "info" en la esquina derecha superior, no aparece del todo oculta.
Es decir, inicialmente no se ve pero si se scrollea hacia la derecha se puede visualizar una pequeña parte de la página de ayuda.

Es un detalle que en realidad no afecta en la visualización porque al entrar en la página el scroll horizontal está hacia la izquierda, pero me pareció informarlo de cualquiera manera.

No se si tendrá que ver con el responsive desing.

Datos tecnicos:
Desde Linux Mint 15, usando Firefox 25.
Resolución del monitor: 1366x768 (16:9)

Dejo una captura para que se entienda mejor:
![screenshot from 2013-11-27 18 34 27](https://f.cloud.github.com/assets/3887467/1634903/cec1b962-57a3-11e3-9763-3a0492653fb5.png)

**Comment by HiroAgustin** [comment]
Parece ser un tema con firefox, lo puedo reproducir tambien en mac.
Trato de vicharlo este finde, muchas gracias!
