### ISSUE TITLE
Generar Readme

### ISSUE THREAD

**Issue by HiroAgustin** [HiroAgustin/DondeReciclo#3]

**Comment by HiroAgustin** [comment]
Agregar info sobre tecnologías usadas

**Comment by danielcarranza** [comment]
Si podés tirame esta info de qué tecnologías se usaron para un documento que estoy armando. Resulta que hoy le pasamos el enlace al sitio a un conocido en Google Argentina y les gustó (en parte porque usa Google Maps) así que nos pidieron un documentito descriptivo en inglés para que ellos lo circulen a la interna.

No me ilusionaría mucho, pero vamos sumando porotos con Google desde hace unos meses, eventualmente le pegaremos un mangazo para algún proyecto copado. :)

**Comment by HiroAgustin** [comment]
En el humans.txt del root estan todas: HTML5 Mobile Boilerplate, Google Maps y donde.js.
Habria que agregar underscore.js pero esta noche tengo pensado deprecar la dependencia ;)

Como 'extras', sobre el software que use para desarrollarlo: Ubuntu el OS, Git para version control, Heroku el hosting y Sublime Text 2 el editor de texto.

Hay una más que todavia no domíno que se llama [Grunt](http://gruntjs.com/) Tengo pensado usarlo para concatenar y minificar los recursos, pero necesito leer un poco mas.

Avisame si necesitas mas data o una mano cno el texto.
Abrazo

**Comment by danielcarranza** [comment]
¡Genial! Apenas lo termine de armar te lo comparto para que puedas verlo o meter mano.

**Comment by danielcarranza** [comment]
Te lo compartí: https://docs.google.com/document/d/1actZtm4RwikKo4Npc4CQwM6drfb1MDc3Q1xuvvleotU/edit#
